### ISSUE TITLE
How to change the number of cpu cores used?

### ISSUE THREAD

**Issue by sebschmi** [medvedevgroup/ESSCompress#2]
Is it possible to change the number of threads used by essCompress? There does not appear to be a flag, and by default it appears to just use all cores.

Alternatively, is it possible to prevent essCompress from running bcalm2 internally, and instead give it the output of bcalm2 as input?

**Comment by amatur** [comment]
To give it the output of bcalm2 as input, you can run the binary essAuxCompress:
./bin/essAuxCompress -i kmers.unitigs.fa -k 30 

Usage: ./essAuxCompress -k <kmer-size> -i <input-file-name> [-v <verbosity level; 0 (DEFAULT): non-verbose, 1: verbose>] [-t <0 (DEFAULT): max compression, 1: fast mode (low compression), 2: output spss only with no compression>]

It does not currently have any flag to change number of threads.

**Comment by amatur** [comment]
Hi, there is no flag for this currently. But a quick workaround would be to make changes in the script bin/essCompress. 
If you want to change the parameters of bcalm2, you can just change all lines containing essAuxBcalm
i.e. in line 112:
/usr/bin/time  -f "%M\t%e" --output-file=mem_bcalm $PPATH/bin/essAuxBcalm -in $L -out kmers -kmer-size $K  -abundance-min $A -verbose 0 > bcalm_output
You can add the option nb-cores change number of cores. You need to do it in all 4 lines that invokes bcalm.

**Comment by sebschmi** [comment]
Alright thanks. I went for running bcalm2 independently now (I got an email with an answer about that even though it does not appear here?).
